### ISSUE TITLE
uninstall not working ?

### ISSUE THREAD

**Issue by changchichung** [Chroma91/machine_setup#71]
my machine_setup.yml
```
temp_dir: "/tmp" # defaults to "~/.machine_setup"
default_shell: "bash" # defaults to "bash"
parallel: true
num_threads: 2
tasks:
  joe:
    commands:
      - run:
          commands:
            install:
              - "sudo apt install -y joe"
            uninstalll:
              - "sudo apt remove joe -y "

```

running machine_setup to install joe
```
chc@cd03:~/git/jammy_bootstrap$ machine_setup install -t joe
[==================================================] 1/1: ✅ joe ➡️ OK  
chc@cd03:~/git/jammy_bootstrap$ 

chc@cd03:~/git/jammy_bootstrap$ joe --help
Joe's Own Editor v4.6

Usage: joe [global-options] [ [local-options] filename ]...

Global options:
    -[-]restore             Restore cursor mode
    -[-]regex               Standard or JOE regular expression syntax
    -[-]square              Rectangular region mode
    -[-]icase               Case insensitive search mode 
    -[-]wrap                Search wraps mode
    -[-]menu_explorer       Menu explorer mode
    -[-]menu_above          Menu above/below mode
    -[-]notagsmenu          Tags menu mode
    -[-]search_prompting    Search prompting mode
    -[-]menu_jump           Jump into menu mode
    -[-]autoswap            Autoswap mode 

```

OK , machine_setup install joe without problems
now let's try to uninstall joe

```
chc@cd03:~/git/jammy_bootstrap$ machine_setup uninstall -t joe
[==================================================] 1/1: ✅ joe ➡️ OK   
chc@cd03:~/git/jammy_bootstrap$ joe --help
Joe's Own Editor v4.6

Usage: joe [global-options] [ [local-options] filename ]...

Global options:
    -[-]restore             Restore cursor mode
    -[-]regex               Standard or JOE regular expression syntax
    -[-]square              Rectangular region mode

```

I don't know why , uninstall return the same messages as install ??
and joe is still there.

any suggestions ??
